DROP TABLE IF EXISTS usuarios;
CREATE TABLE usuarios (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS tareas;
CREATE TABLE tareas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion TEXT NOT NULL,
  estado BOOLEAN NOT NULL DEFAULT FALSE,
  usuarioregistra INT NOT NULL,
  usuarioactualiza INT,
  fecharegistra TIMESTAMP NOT NULL DEFAULT NOW(),
  fechaactualiza TIMESTAMP
);

DROP TABLE IF EXISTS logs;  
CREATE TABLE logs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion TEXT NOT NULL,
  usuarioregistra INT NOT NULL,
  fecharegistra TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE tareas
  ADD FOREIGN KEY (usuarioregistra) REFERENCES usuarios(id);

ALTER TABLE tareas
  ADD FOREIGN KEY (usuarioactualiza) REFERENCES usuarios(id);

ALTER TABLE logs
  ADD FOREIGN KEY (usuarioregistra) REFERENCES usuarios(id);


INSERT INTO usuarios (nombre) VALUES ('admin');